# Generated by Django 4.0.4 on 2023-10-23 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'build_cardtype',
            },
        ),
        migrations.CreateModel(
            name='EventCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'event_cardtype',
            },
        ),
        migrations.CreateModel(
            name='VappCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vapp_cardtype',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vehicle_type',
            },
        ),
        migrations.CreateModel(
            name='VappRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('company', models.TextField(null=True)),
                ('mobile', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('vehicle_number', models.TextField(null=True)),
                ('id_proof_front', models.FileField(null=True, upload_to='id-proof-front/')),
                ('id_proof_back', models.FileField(null=True, upload_to='id-proof-back/')),
                ('vehicle_pass', models.FileField(null=True, upload_to='vehicle_pass/')),
                ('delivery_date', models.DateField(null=True)),
                ('remark', models.TextField(default='', null=True)),
                ('collected', models.BooleanField(default=False)),
                ('print_count', models.IntegerField(default=0)),
                ('verification', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cardtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.vappcardtype')),
                ('vehicletype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.vehicletype')),
            ],
            options={
                'db_table': 'vapp_registrations',
            },
        ),
        migrations.CreateModel(
            name='EventRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('company', models.TextField(null=True)),
                ('dob', models.DateField(null=True)),
                ('nationality', models.TextField(null=True)),
                ('mobile', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('id_proof_expiry', models.DateField(null=True)),
                ('id_proof_type', models.CharField(choices=[('Passport-Id', 'Passport-Id'), ('Emirates-Id', 'Emirates-Id')], default='Emirates-Id', max_length=50)),
                ('id_proof_number', models.TextField(null=True)),
                ('id_proof_front', models.FileField(null=True, upload_to='id-proof-front/')),
                ('id_proof_back', models.FileField(null=True, upload_to='id-proof-back/')),
                ('badge_photo', models.FileField(null=True, upload_to='badge-images/')),
                ('remark', models.TextField(default='', null=True)),
                ('collected', models.BooleanField(default=False)),
                ('print_count', models.IntegerField(default=0)),
                ('verification', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cardtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.eventcardtype')),
            ],
            options={
                'db_table': 'event_registrations',
            },
        ),
        migrations.CreateModel(
            name='BuildRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('mobile', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
                ('dob', models.DateField(null=True)),
                ('remark', models.TextField(default='', null=True)),
                ('collected', models.BooleanField(default=False)),
                ('print_count', models.IntegerField(default=0)),
                ('verification', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cardtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.buildcardtype')),
            ],
            options={
                'db_table': 'build_registrations',
            },
        ),
        migrations.AddField(
            model_name='buildcardtype',
            name='eventcardtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.eventcardtype'),
        ),
    ]
