# Generated by Django 4.0.4 on 2023-10-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_locations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
