# Generated by Django 4.0.4 on 2023-10-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_locations_buildregistrations_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildregistrations',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.locations'),
        ),
        migrations.AlterField(
            model_name='eventregistrations',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.locations'),
        ),
        migrations.AlterField(
            model_name='vappregistrations',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.locations'),
        ),
    ]
