# Generated by Django 4.0.4 on 2023-10-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_buildregistrations_location_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locations',
            table='locations',
        ),
    ]
