# Generated by Django 4.0.4 on 2023-11-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_locations_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildcardtype',
            name='eventcardtype',
        ),
    ]
