# Generated by Django 4.0.4 on 2023-11-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_buildcardtype_eventcardtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildregistrations',
            name='id_proof_back',
            field=models.FileField(null=True, upload_to='id-proof-back/'),
        ),
        migrations.AddField(
            model_name='buildregistrations',
            name='id_proof_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='buildregistrations',
            name='id_proof_front',
            field=models.FileField(null=True, upload_to='id-proof-front/'),
        ),
        migrations.AddField(
            model_name='buildregistrations',
            name='id_proof_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='buildregistrations',
            name='id_proof_type',
            field=models.CharField(choices=[('Passport-Id', 'Passport-Id'), ('Emirates-Id', 'Emirates-Id')], default='Emirates-Id', max_length=50),
        ),
    ]
