# Generated by Django 4.0.4 on 2023-11-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_buildregistrations_id_proof_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vappregistrations',
            name='delivery_from_date',
            field=models.DateField(default=models.DateField(null=True), null=True),
        ),
        migrations.AddField(
            model_name='vappregistrations',
            name='delivery_to_date',
            field=models.DateField(null=True),
        ),
    ]
