# Generated by Django 4.0.4 on 2023-11-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_vappregistrations_delivery_from_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vappregistrations',
            name='delivery_from_date',
        ),
        migrations.RemoveField(
            model_name='vappregistrations',
            name='delivery_to_date',
        ),
    ]
