# Generated by Django 4.0.4 on 2023-11-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_vappregistrations_delivery_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vappregistrations',
            name='delivery_from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vappregistrations',
            name='delivery_to_date',
            field=models.DateField(null=True),
        ),
    ]
